services:
  bt_analytics_db:
    container_name: bt_analytics_db
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=bt_analytics
    ports:
      - "5433:5433"
    expose:
      - "5433"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U floofydoggo -d bt_analytics'"]
      interval: 10s
      timeout: 3s
      retries: 3
    hostname: bt_analytics_db
    networks:
      - server-side
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 4.4.4.4

  bt_analytics_main:
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 4.4.4.4
    container_name: bt_analytics_main
    image: bt_analytics_main
    depends_on: 
      bt_analytics_db:
        condition: service_healthy
    ports: 
      - "3000:3000"
    networks:
      - server-side
    environment:
      - PG_USER=floofydoggo
      - PG_PASSWORD=bottle273
      - PG_DBNAME=bt_analytics
      - PG_HOST=bt_analytics_db
      - RUST_BACKTRACE=full
networks:
  server-side: {}
